### ISSUE TITLE
Problems installing on Windows 10

### ISSUE THREAD

**Issue by eduardoflorence** [Norbert515/detective#4]
I'm trying to install on Windows with the command:

```
flutter pub global activate -sgit https://github.com/Norbert515/detective.git
```

But I get this error:

```
Resolving dependencies...
+ detective 0.0.0 from git https://github.com/Norbert515/detective.git at f0d0ab
+ path 1.7.0
Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: O pipe está sendo fechado.
, errno = 232)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:309:15)
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#8      _StreamController._add (dart:async/stream_controller.dart:682:7)
#9      _StreamController.add (dart:async/stream_controller.dart:624:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:156:17)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:289:5)
#12     _IOSinkImpl.writeln (dart:io/io_sink.dart:309:5)
#13     _StdSink.writeln (dart:io/stdio.dart:342:11)
#14     _printToStream (package:pub/src/log.dart:508:10)
#15     _logToStream (package:pub/src/log.dart:492:3)
#16     _logToStdout (package:pub/src/log.dart:471:3)
#17     write (package:pub/src/log.dart:234:27)
#18     new Progress (package:pub/src/progress.dart:49:7)
#19     progress (package:pub/src/log.dart:360:18)
#20     Entrypoint.precompileExecutables (package:pub/src/entrypoint.dart:323:11)
#21     GlobalPackages._installInCache (package:pub/src/global_packages.dart:221:22)
<asynchronous suspension>
#22     GlobalPackages.activateGit (package:pub/src/global_packages.dart:95:11)
<asynchronous suspension>
#23     GlobalActivateCommand.run (package:pub/src/command/global_activate.dart:101:24)
#24     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#25     PubCommandRunner.runCommand.<anonymous closure> (package:pub/src/command_runner.dart:182:39)
#26     new Future.sync (dart:async/future.dart:223:31)
#27     captureErrors.wrappedCallback (package:pub/src/utils.dart:113:12)
#28     _rootRun (dart:async/zone.dart:1190:13)
#29     _CustomZone.run (dart:async/zone.dart:1093:19)
#30     _runZoned (dart:async/zone.dart:1630:10)
#31     runZonedGuarded (dart:async/zone.dart:1618:12)
#32     runZoned (dart:async/zone.dart:1547:12)
#33     captureErrors (package:pub/src/utils.dart:130:5)
#34     PubCommandRunner.runCommand (package:pub/src/command_runner.dart:182:13)
<asynchronous suspension>
#35     PubCommandRunner.run (package:pub/src/command_runner.dart:132:11)
#36     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart:8:22)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Comment by eduardoflorence** [comment]
I managed to solve by installing through Windows PowerShell instead of the Terminal (CMD)
